import esbuild from 'esbuild'
import process from 'process'
import builtins from 'builtin-modules'
import { copyFileSync } from 'fs'

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`

const prod = process.argv[2] === 'production'

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  outdir: 'out',
  entryPoints: ['src/main.ts', 'src/main.test.ts'],
  bundle: true,
  external: ['vscode', 'electron', ...builtins],
  platform: 'node',
  format: 'cjs',
  target: 'es2018',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
})

if (prod) {
  await context.rebuild()
  copyFileSync('package.json', 'out/package.json')
  process.exit(0)
} else {
  await context.watch()
  copyFileSync('package.json', 'out/package.json')
}
