name: Build Tabula.go

on:
  push:
    branches-ignore:
      - main
    paths:
      - ".github/workflows/tabula.go.yaml"
      - "cmd/**"
      - "internal/**"
  workflow_dispatch:

env:
  GO_VERSION: "1.22.x"

jobs:
  tabula_go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: go-mod-cache-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-mod-cache-${{ runner.os }}-
      - name: Install dependencies
        run: go mod download
      - name: Run vet
        uses: extractions/setup-just@v3
        run: just vet
      - name: Run tests
        uses: extractions/setup-just@v3
        run: just test
      - name: Build Go binary
        uses: extractions/setup-just@v3
        run: just build-linux-amd64
