name: Build Tabula.vscode

on:
  push:
    branches-ignore:
      - main
    paths:
      - ".github/workflows/tabula.vscode.yaml"
      - "plugins/tabula.vscode/**"
  workflow_dispatch:

env:
  NODE_VERSION: 20.x

jobs:
  tabula_vscode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: plugins/tabula.vscode/package-lock.json

      - uses: extractions/setup-just@v3

      - name: Install dependencies
        run: just setup-vscode

      - name: Lint
        run: just lint-vscode

      - name: Run tests with xvfb
        working-directory: plugins/tabula.vscode
        run: |
          xvfb-run -a --server-args="-screen 0 1920x1080x24" npm test
      - name: Build
        run: just build-vscode

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tabula_vscode
          path: plugins/tabula.vscode/out/
