name: Test Tabula

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

on:
  push:
    branches-ignore:
      - main
    paths:
      - "cmd/**"
      - "internal/**"
      - "Makefile"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/tabula.yml"
  pull_request:
    branches-ignore:
      - main
    paths:
      - "cmd/**"
      - "internal/**"
      - "Makefile"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/tabula.yml"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.2"

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: go-mod-cache-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-mod-cache-${{ runner.os }}-

      - name: Install dependencies
        run: go mod download

      - name: Run vet
        run: make vet

      - name: Run Tests
        run: make test

      - name: Build Executable
        run: make build
