name: Build Tabula.obsidian

on:
  push:
    branches-ignore:
      - main
    paths:
      - ".github/workflows/tabula.obsidian.yaml"
      - "plugins/tabula.obsidian/**"
  workflow_dispatch:

env:
  NODE_VERSION: 20.x

jobs:
  tabula_obsidian:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: plugins/tabula.obsidian/package-lock.json
      - uses: extractions/setup-just@v3

      - name: Build obsidian
        run: just obsidian
