name: Build Tabula.go

on:
  push:
    branches-ignore:
      - main
    paths:
      - ".github/workflows/tabula.go.yaml"
      - "cmd/**"
      - "internal/**"
  workflow_dispatch:

env:
  GO_VERSION: "1.22.x"

jobs:
  tabula_go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: go-mod-cache-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-mod-cache-${{ runner.os }}-
      - uses: extractions/setup-just@v3
      - name: Install dependencies
        run: just setup-go

      - name: use golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.8.0

      - name: lint
        run: just lint-go

      - name: Run tests
        run: just test-go

      - name: Build Go binary
        run: just build-linux-amd64
